	
service: api-gateway-talk-lambda-dependencies

frameworkVersion: '3.37.0'

provider:
  name: aws
  region: ap-south-1
 
layers:
  api_gateway_dependencies:
    path: api_gateway_dependencies # required, path to layer contents on disk
    name:  api_gateway_dependencies_layer # optional, Deployed Lambda layer name
    description: Lambda layer dependencies for API gateway talk # optional, Description to publish to AWS
    compatibleRuntimes: # optional, a list of runtimes this layer is compatible with
      - python3.10
    compatibleArchitectures: # optional, a list of architectures this layer is compatible with
      - x86_64
      - arm64
    retain: true # optional, false by default. If true, layer versions are not deleted as new ones are created
